name: PipelineWorkflow

on:
 push:
   branches:
   - main
pull_request:
   branches:
   - main

jobs:
    build:
    name: Azure Pipeline
    runs-on: Wwindows-latest
    steps:
    - name: Azure Pipelines Action
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: https://dev.azure.com/ClouddeploySpace/DevProject
        azure-pipeline-name: 'WebApp02'
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN}}
